package udistrital.avanzada.taller.vista;

import java.awt.CardLayout;

/**
 * Clase {@code MainForm} representa el panel principal de la aplicación.
 *
 * <p>
 * Este panel funciona como un contenedor que administra las diferentes vistas o
 * secciones del programa (Inicio,Cargar)
 * utilizando un {@link java.awt.CardLayout}. De esta manera, solo se muestra un
 * panel a la vez y se puede cambiar fácilmente entre ellos.</p>
 *
 * <p>
 * El uso de {@code CardLayout} permite una navegación sencilla y ordenada
 * dentro de la interfaz gráfica.</p>
 *
 * @author Paula Martínez
 * @version 1.0
 * @since 2025-10-25
 */
public class MainForm extends javax.swing.JPanel {

    /**
     * Panel que muestra la vista de inicio.
     */
    private PanelInicio inicio;
    /**
     * Panel que muestra la vista de inicio.
     */
    private PanelCargar cargar;
    
    /**
     * Layout que controla qué panel se muestra actualmente.
     */
    private CardLayout layout;

    /**
     * Constructor de la clase {@code MainForm}.
     *
     * <p>
     * Inicializa el layout principal como {@code CardLayout}, crea las
     * instancias de todos los subpaneles y muestra el panel de inicio por
     * defecto.</p>
     */
    public MainForm() {
        layout = new CardLayout(); // Se usa CardLayout para manejar las "pantallas"
        setLayout(layout);
        initPanels();
        mostrarPanelInicio(); // Muestra el panel de inicio al abrir la aplicación
    }

    /**
     * Inicializa los diferentes subpaneles del formulario principal y los añade
     * al {@code CardLayout} con un nombre identificador.
     */
    private void initPanels() {
        inicio = new PanelInicio();
        cargar = new PanelCargar();
        

        // Se añaden al contenedor con un identificador único
        add(inicio, "Inicio");
        add(cargar, "Cargar");
    }

    // ---------------- MÉTODOS PARA MOSTRAR LOS PANELES ----------------
    /**
     * Muestra el panel de inicio.
     */
    public void mostrarPanelInicio() {
        layout.show(this, "Inicio");
    }
    /**
     * Muestra el panel de carga de propiedades.
     */
    public void mostrarPanelCargar() {
        layout.show(this, "Cargar");
    }

    // ---------------- MÉTODOS GETTERS ----------------
    /**
     * Obtiene el panel de inicio.
     *
     * @return instancia de {@link PanelInicio}
     */
    public PanelInicio getPanelInicio() {
        return inicio;
    }
    /**
     * Obtiene el panel de cargar.
     *
     * @return instancia de {@link PanelCargar}
     */
    public PanelCargar getPanelCargar() {
        return cargar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
