package udistrital.avanzada.taller.vista;

import javax.swing.JButton;

/**
 * Panel de inicio de <b>ConjurosConHilos</b>.
 * <p>
 * Esta vista actúa como pantalla principal del menú inicial. Presenta el título
 * del juego y dos acciones básicas: <em>JUGAR</em> (para continuar al flujo del
 * torneo) y <em>SALIR</em> (para cerrar la aplicación).
 * </p>
 *
 * <p>
 * Hereda de {@link PanelBase}, por lo que adopta el fondo gráfico común a toda
 * la interfaz. Siguiendo el patrón MVC, este panel no contiene lógica de
 * negocio: expone getters de sus botones para que el controlador asigne los
 * listeners y orqueste el flujo.
 * </p>
 *
 * <p>
 * Nota: el método {@code initComponents()} y la disposición de los componentes
 * han sido generados por el GUI Builder de NetBeans y no deben modificarse
 * manualmente, a fin de preservar la integridad del diseñador visual.
 * </p>
 *
 * @author Paula Martinez
 * @version 6.0
 * @since 2025-10-25
 */
public class PanelInicio extends PanelBase {

    /**
     * Crea el panel de inicio e inicializa sus componentes gráficos.
     * <p>
     * La inicialización de componentes es responsabilidad del GUI Builder
     * (NetBeans). Este constructor no debe incorporar lógica de negocio ni
     * registros de eventos; únicamente prepara la vista para que el controlador
     * asigne los manejadores de acción.
     * </p>
     */
    public PanelInicio() {
        initComponents();
    }

    /**
     * Devuelve la referencia al botón <strong>SALIR</strong> para que el
     * controlador pueda registrar su listener y manejar el cierre de la
     * aplicación.
     *
     * @return la instancia del botón de salida
     */
    public JButton getBotonSalir() {
        return botonSalir;
    }

    /**
     * Devuelve la referencia al botón <strong>JUGAR</strong> para que el
     * controlador pueda registrar su listener y continuar al siguiente paso del
     * flujo (p. ej., carga de datos o pantalla de duelo).
     *
     * @return la instancia del botón de inicio/juego
     */
    public JButton getBotonJugar() {
        return botonJugar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSalir = new javax.swing.JButton();
        botonJugar = new javax.swing.JButton();
        lTitulo = new javax.swing.JLabel();

        botonSalir.setBackground(new java.awt.Color(132, 72, 62));
        botonSalir.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(153, 0, 0));
        botonSalir.setText("SALIR");
        botonSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        botonJugar.setBackground(new java.awt.Color(132, 72, 62));
        botonJugar.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        botonJugar.setForeground(new java.awt.Color(0, 0, 0));
        botonJugar.setText("JUGAR");
        botonJugar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        lTitulo.setFont(new java.awt.Font("Monospaced", 1, 60)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("Conjuros Con Hilos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(487, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(482, 482, 482))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lTitulo)
                .addGap(181, 181, 181)
                .addComponent(botonJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel lTitulo;
    // End of variables declaration//GEN-END:variables
}
