package udistrital.avanzada.taller.vista;

import javax.swing.JButton;

/**
 *
 * @author paisa
 */
public class PanelCargar extends PanelBase {

    /**
     * Creates new form PanelCargar
     */
    public PanelCargar() {
        initComponents();
    }

    /**
     * Devuelve la referencia al botón <strong>SALIR</strong> para que el
     * controlador pueda registrar su listener y manejar el cierre de la
     * aplicación.
     *
     * @return la instancia del botón de salida
     */
    public JButton getBotonSalir() {
        return botonSalir;
    }

    /**
     * Devuelve la referencia al botón <strong>JUGAR</strong> para que el
     * controlador pueda registrar su listener y continuar al siguiente paso del
     * flujo (p. ej., carga de datos o pantalla de duelo).
     *
     * @return la instancia del botón de inicio/juego
     */
    public JButton getBotonJugar() {
        return botonJugar;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulo = new javax.swing.JLabel();
        botonCargarHechizos = new javax.swing.JButton();
        botonCargarMagos = new javax.swing.JButton();
        botonJugar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        lTitulo.setFont(new java.awt.Font("Monospaced", 1, 60)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("Cargar Propiedades");

        botonCargarHechizos.setBackground(new java.awt.Color(132, 72, 62));
        botonCargarHechizos.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        botonCargarHechizos.setForeground(new java.awt.Color(0, 0, 0));
        botonCargarHechizos.setText("Cargar Hechizos");
        botonCargarHechizos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        botonCargarMagos.setBackground(new java.awt.Color(132, 72, 62));
        botonCargarMagos.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        botonCargarMagos.setForeground(new java.awt.Color(0, 0, 0));
        botonCargarMagos.setText("Cargar Magos");
        botonCargarMagos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        botonJugar.setBackground(new java.awt.Color(132, 72, 62));
        botonJugar.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        botonJugar.setForeground(new java.awt.Color(0, 0, 0));
        botonJugar.setText("JUGAR");
        botonJugar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        botonSalir.setBackground(new java.awt.Color(132, 72, 62));
        botonSalir.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(153, 0, 0));
        botonSalir.setText("SALIR");
        botonSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(482, 482, 482)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCargarMagos, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCargarHechizos, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(487, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lTitulo)
                .addGap(92, 92, 92)
                .addComponent(botonCargarHechizos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCargarMagos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarHechizos;
    private javax.swing.JButton botonCargarMagos;
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel lTitulo;
    // End of variables declaration//GEN-END:variables
}
